name: travelpy
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - pandas=2.2.*
  - numpy=1.26.*
  - matplotlib=3.8.*
  - pytest=8.*
  - pytest-cov
  - pytest-raises
  - pytest-randomly
  - pytest-xdist
  - hatch
  - pre-commit
  - ruff
  - pip
  - pip:
    - quartodoc
    - pip-audit
    - twine
